version: "2"

run:
  timeout: 10m
  go: "1.24"
  tests: true

linters:
  default: standard
  enable:
    - errcheck
    - govet
    - ineffassign
    - unused

issues:
  max-issues-per-linter: 10
  max-same-issues: 3
  exclude-rules:
    # Exclude all test files from linting due to Go version compatibility
    - path: _test\.go
      linters:
        - all

output:
  format: colored-line-number
  print-linter-name: true
  sort-results: true